drop table if  exists `hotel_customers`;
create table if not exists `hotel_customers` 
(
`Name`              VARCHAR(100)  ,
`CardNo`            INT  ,
`Descriot`          VARCHAR(100)  ,
`CtfTp`             VARCHAR(100)  ,
`CtfId`             VARCHAR(100)  ,
`Gender`            VARCHAR(100)  ,
`Birthday`          INT  ,
`Address`          VARCHAR(400)  ,
`Zip`               VARCHAR(100)  ,
`Dirty`             VARCHAR(100)  ,
`District1`         VARCHAR(100)  ,
`District2`         VARCHAR(100)  ,
`District3`         INT  ,
`District4`         INT  ,
`District5`         VARCHAR(100)  ,
`District6`         VARCHAR(100)  ,
`FirstNm`           VARCHAR(100)  ,
`LastNm`            VARCHAR(100)  ,
`Duty`              VARCHAR(100)  ,
`Mobile`            INT  ,
`Tel`               VARCHAR(100)  ,
`Fax`               VARCHAR(100)  ,
`EMail`             VARCHAR(100)  ,
`Nation`            VARCHAR(100)  ,
`Taste`             VARCHAR(100)  ,
`Education`         VARCHAR(100)  ,
`Company`           VARCHAR(100)  ,
`CTel`              VARCHAR(100)  ,
`CAddress`          VARCHAR(100)  ,
`CZip`              VARCHAR(100)  ,
`Family`            VARCHAR(100)  ,
`Version`           DATE          ,
`id`                INT NOT NULL primary key
);